# manabot/conf/config.yaml

defaults:
  - observation: default
  - match: default
  - train: default
  - reward: default
  - agent: default
  - experiment: default

train:
  num_envs: 4
  num_steps: 16
  total_timesteps: 10000
  learning_rate: 2.5e-4

experiment:
  exp_name: "quick_train"
  device: "cpu"
  profiler_enabled: True

hydra:
  run:
    dir: ${experiment.runs_dir}/${experiment.exp_name}/${hydra.job.name}_${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True
